name: Generate Real Madrid Content

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate content
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: node scripts/content-generator.js
      
    - name: Commit and push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "🤖 Auto-generate Real Madrid content - $(date +'%Y-%m-%d %H:%M')"
          git push
        else
          echo "No changes to commit"
        fi
